# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-10-20 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_auto_20181020_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='used_tickets',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
